#!/usr/bin/env bash

function copyandecho {
    xclip -selection clipboard -t image/png -i $1
    echo $1
}

function shootregion {
    filename="/tmp/${1:-Screenshot-$(date | sed 's/[ :]/-/g')}.png"
    eval $(crud)
    import -crop $G -window root $filename
    convert -profile $HOME/.colors/N140HCA_EAB_01.icm $filename $filename
    copyandecho $filename
}

function shootfull {
    filename="/tmp/${1:-Screenshot-$(date | sed 's/[ :]/-/g')}.png"
    import -window root $filename
    convert -profile $HOME/.colors/N140HCA_EAB_01.icm $filename $filename
    copyandecho $filename
}

export -f shootregion
export -f shootfull
export -f copyandecho
